# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/anime_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root2003

# Configuración de Hibernate / JPA
# "update" creará/actualizará las tablas automáticamente basado en tus @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto del servidor (distinto a Next.js que usa el 3000)
server.port=8080

# ==========================================
# CONFIGURACIÓN DEL BOT DE TELEGRAM
# ==========================================
telegram.bot.username=twainf_bot
telegram.bot.token=8895601725:AAHIgZ2rGS3ehDt_p9HBnaRPbdBSPbPVkF8
# Si tu canal es público, usa el @. Ejemplo: @mi_canal_anime. Si es privado, usa su ID numérico (ej: -100123456789)
telegram.channel.id=-1004460671301